<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-27T21:40:06 IST" name="Default suite" finished-at="2024-09-27T21:40:23 IST" duration-ms="17709">
    <groups>
      <group name="error-case">
        <method signature="BmiCalculatorTest.calculateAgeTest()[pri:0, instance:practisetest.BmiCalculatorTest@45752059]" name="calculateAgeTest" class="practisetest.BmiCalculatorTest"/>
      </group> <!-- error-case -->
    </groups>
    <test started-at="2024-09-27T21:40:06 IST" name="Default test" finished-at="2024-09-27T21:40:23 IST" duration-ms="17709">
      <class name="practisetest.BmiCalculatorTest">
        <test-method is-config="true" signature="extentReportSetUp()[pri:0, instance:practisetest.BmiCalculatorTest@45752059]" started-at="2024-09-27T21:40:06 IST" name="extentReportSetUp" finished-at="2024-09-27T21:40:06 IST" duration-ms="13" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extentReportSetUp -->
        <test-method is-config="true" signature="startDriver(org.testng.ITestContext)[pri:0, instance:practisetest.BmiCalculatorTest@45752059]" started-at="2024-09-27T21:40:06 IST" name="startDriver" finished-at="2024-09-27T21:40:21 IST" duration-ms="14508" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@2121d1f9]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startDriver -->
        <test-method signature="calculateAgeTest()[pri:0, instance:practisetest.BmiCalculatorTest@45752059]" started-at="2024-09-27T21:40:21 IST" name="calculateAgeTest" finished-at="2024-09-27T21:40:22 IST" duration-ms="1661" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Weight error did not match actualtext expected [Please enter a valid weight between 20 kg and 300 kg.] but found []]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Weight error did not match actualtext expected [Please enter a valid weight between 20 kg and 300 kg.] but found []
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at practisetest.BmiCalculatorTest.calculateAgeTest(BmiCalculatorTest.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- calculateAgeTest -->
        <test-method is-config="true" signature="quitDriver()[pri:0, instance:practisetest.BmiCalculatorTest@45752059]" started-at="2024-09-27T21:40:22 IST" name="quitDriver" finished-at="2024-09-27T21:40:23 IST" duration-ms="284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitDriver -->
        <test-method is-config="true" signature="flushExtenReports()[pri:0, instance:practisetest.BmiCalculatorTest@45752059]" started-at="2024-09-27T21:40:23 IST" name="flushExtenReports" finished-at="2024-09-27T21:40:23 IST" duration-ms="595" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flushExtenReports -->
      </class> <!-- practisetest.BmiCalculatorTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
